### ISSUE TITLE
Missing lat for Micronesia states

### ISSUE THREAD

**Issue by bodyslam** [crhallberg/zips#5]
Hi by accident I've found that you have `null` lat values and the same long values for Micronesia islands (in zip-tree.json):

```javascript
{"zip":"96941","city":"Pohnpei","state":"FM","lat":null,"long":151.5031},{"zip":"96942","city":"Chuuk","state":"FM","lat":null,"long":151.5031},{"zip":"96943","city":"Yap","state":"FM","lat":null,"long":151.5031},{"zip":"96944","city":"Kosrae","state":"FM","lat":null,"long":151.5031}
```

I've gone ahead and searched and filled in these values for you
```json
{"zip":"96941","city":"Pohnpei","state":"FM","lat":6.8541,"long":158.2624},{"zip":"96942","city":"Chuuk","state":"FM","lat":7.4170,"long":151.7830},{"zip":"96943","city":"Yap","state":"FM","lat":9.5557,"long":138.1399},{"zip":"96944","city":"Kosrae","state":"FM","lat":5.3096,"long":162.9815}
```

Could you update the data with these values? I'm also assuming some work will need to be done in `loc-tree.json`.

Thanks

**Comment by crhallberg** [comment]
Thank you! I added your fixes here: d4804202c3f0c66918bafd99fc1d24c32aeaca19.

I'm currently working on a new way to load and query this information, so check out the [quadtree branch for updated data](https://github.com/crhallberg/zips/tree/quadtree/data)! Thanks again!
