### ISSUE TITLE
Question - where to put const zips = require("zips");

### ISSUE THREAD

**Issue by 12cassie34** [crhallberg/zips#6]
Hello Chris,

Thanks for creating this useful package.

I'm new to code, and sorry for asking this stupid question...

I'm using laravel for my project.

I have installed the package via npm, but I'm stuck in where to put  `const zips = require("zips"); ` to let the package work.

Could you help me?

**Comment by crhallberg** [comment]
I apologize for getting back to you after so long. I wrote zips to be used with server-side Javascript so integrating it with a PHP framework could be tricky. 

Without knowing more about your project, you could try to use [Javascript modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) or [build tools](https://ui.dev/webpack/) to load this project into the front end. It may be better for your time and effort to try to find a PHP solution ([like maybe this one](https://github.com/axlon/laravel-postal-code-validation)) or find a frontend library that can help you with less setup.

If I make this project easier to use on the front end, I'll let you know!
