### ISSUE TITLE
Question - example on how to generate the tree for zip-tree.json

### ISSUE THREAD

**Issue by davydaenen** [crhallberg/zips#7]
Hi!

I am interested on how you were able to generate the tree data in [zip-tree.json] based on Geonames. Do you have an example for that?

Thanks.

**Comment by crhallberg** [comment]
Hello! I hope this helps!

The first step is getting the [data from Geonames](https://download.geonames.org/export/zip/). Here is an example of the data:

```TSV
US	99553	Akutan		Alaska	AK	Aleutians East	013			54.143	-165.7854	1
US	99571	Cold Bay	Alaska	AK	Aleutians East	013			55.1858	-162.7211	1
US	99583	False Pass	Alaska	AK	Aleutians East	013			54.8542	-163.4113	1
US	99612	King Cove	Alaska	AK	Aleutians East	013			55.0628	-162.3056	1
```

Each of these is turned into a JSON object that contains the information we want.

```JSON
[
    {"zip":"99553","city":"Akutan","state":"AK","lat":54.143,"long":-165.7854},
    {"zip":"99571","city":"Cold Bay","state":"AK","lat":55.1858,"long":-162.7211},
    {"zip":"99583","city":"False Pass","state":"AK","lat":54.841,"long":-163.4368},
    {"zip":"99612","city":"King Cove","state":"AK","lat":55.0628,"long":-162.3056},
    ...
]
```

From here, the transformation into `zip-tree.json` is - in hindsight - crude. Each zipcode is broken into 5 numbers and spread into a nested tree.

```js
zipTree[9][9][5][5][3] = { "zip": "99553", "city": "Akutan", "state": "AK", "lat": 54.143, "long": -165.7854 };
```

`loc-tree.json` is broken into a strict grid by absolute rounded lat and long. This allows us to search a much smaller set for the closest zip code by location, but perhaps a more robust QuadTree would be better.

```js
locTree[54][165] = { "zip": "99553", "city": "Akutan", "state": "AK", "lat": 54.143, "long": -165.7854 };
```

I see lots of room for improvement 5 years later, but I hope this helps!

**Comment by davydaenen** [comment]
Thanks, this definitely helped and gave some insight. 

I am currently only focused on retrieving based on zipcode, but extra steps for location based might come in handy later too!

Cheers
